---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300M
efiSystemPartitionName: EFI

userSwapChoices:
  - none
  - small
  - suspend
  - file

defaultFileSystemType: "btrfs"

availableFileSystemTypes: ["ext4", "btrfs"]

drawNestedPartitions: false
alwaysShowPartitionLabels: true
enableLuksAutomatedPartitioning: true

initialPartitioningChoice: erase
initialSwapChoice: small
