---
services:
  - name: NetworkManager
    mandatory: true
  - name: sddm
    mandatory: true
  - name: bluetooth
    mandatory: false
  - name: cups
    mandatory: false
  - name: cups-browsed
    mandatory: false
  - name: avahi-daemon
    mandatory: false
  - name: keyd
    mandatory: false
  - name: ufw
    mandatory: false

targets:
  - name: multi-user
    mandatory: true
