---
# Führt den Befehl innerhalb des neu installierten Systems (chroot) aus
dontChroot: false

# Timeout in Sekunden
timeout: 10

script:
    # Das Minuszeichen '-' vor dem Befehl ist wichtig:
    # Es sorgt dafür, dass die Installation NICHT abbricht, 
    # falls Avahi aus irgendeinem Grund gar nicht installiert sein sollte.
    - "-systemctl mask avahi-daemon.socket avahi-daemon.service"

i18n:
    name: "Maskiere Avahi mDNS-Dienste (Netzwerk-Fix)..."
