---
dontChroot: false
timeout: 10

script:
    # Sicherstellen, dass nichts maskiert ist
    - "-systemctl unmask avahi-daemon.socket avahi-daemon.service"
    # Avahi für Drucker-Discovery aktivieren
    - "-systemctl enable avahi-daemon.socket avahi-daemon.service"

i18n:
    name: "Aktiviere Avahi mDNS-Dienste (Drucker-Erkennung)..."