---
defaultGroups:
  - wheel
  - seat
  - video
  - audio
  - input
  - storage
  - optical
  - network
  - power
  - rfkill
  - lp

autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
passwordRequirements:
  minLength: 4

userShell: /bin/bash
