preload = /home/hopx/.config/hypr/wallpapers/windows-7-x-arch-linux-fi-1498276061.jpg

wallpaper {
    monitor = eDP-1
    path = /home/hopx/.config/hypr/wallpapers/windows-7-x-arch-linux-fi-1498276061.jpg
    fit_mode = cover
}

splash = false
