[hyprglass]
enabled = true
failed = false
filename = 'hyprglass.so'

[repository]
author = 'hyprnux'
hash = '22acd5db6ef73fa34cad2d5ce8b76cf37e9acaa5'
name = 'HyprGlass'
rev = ''
url = 'https://github.com/hyprnux/hyprglass'