[hyprgrass]
enabled = true
failed = false
filename = 'hyprgrass.so'

[hyprgrass-backlight]
enabled = false
failed = false
filename = 'hyprgrass-backlight.so'

[hyprgrass-pulse]
enabled = false
failed = false
filename = 'hyprgrass-pulse.so'

[repository]
author = 'horriblename'
hash = 'e28346f49144e058b0e2d9dc66313c0a57c3d423'
name = 'hyprgrass'
rev = ''
url = 'https://github.com/horriblename/hyprgrass'