#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

insmod png
loadfont ($root)/grub/themes/trafktux/fonts/notosans-bold-28.pf2
loadfont ($root)/grub/themes/trafktux/fonts/notosans-14.pf2
loadfont ($root)/grub/themes/trafktux/fonts/notosans-bold-16.pf2
